linters:
  enable:
    - contextcheck
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - containedctx
    - dupl
    - durationcheck
    - errname
    - exhaustive
    - forcetypeassert
    - godot
    - gofmt
    - goheader
    - goprintffuncname
    - gosec
    - musttag
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - tenv
    - testableexamples
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
    - wsl

linters-settings:
  wsl:
    allow-assign-and-call: false
    strict-append: false
  revive:
    rules:
      - name: blank-imports
        disabled: true

issues:
  exclude:
    - "if statements should only be cuddled with assignments" # from wsl
    - "if statements should only be cuddled with assignments used in the if statement itself" # from wsl
    - "assignments should only be cuddled with other assignments" # from wsl. false positive case: var a bool\nb := true
    - "declarations should never be cuddled" # from wsl

